# Assignment I: Numpy

Perform the follwing tasks:


In [12]:
#1: import the numpy library
import numpy as np

In [13]:
#2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.9808211 , 0.1589114 , 0.07221844, 0.29289933, 0.65513343,
        0.65698947, 0.01231679, 0.65458402, 0.92888689, 0.31771102],
       [0.37258478, 0.40761305, 0.04598827, 0.21164715, 0.30157051,
        0.90088609, 0.7644569 , 0.83998914, 0.013556  , 0.36561257],
       [0.5937094 , 0.00675928, 0.10648805, 0.49602118, 0.90294554,
        0.45143813, 0.99901168, 0.40917879, 0.4047026 , 0.41391488],
       [0.82109095, 0.13065452, 0.13905245, 0.87673089, 0.48683184,
        0.57976776, 0.28369693, 0.66041372, 0.04976711, 0.29454154],
       [0.90843183, 0.66761541, 0.84768839, 0.096319  , 0.05139835,
        0.75883449, 0.39422467, 0.07695471, 0.23141037, 0.84866362],
       [0.65197707, 0.78379943, 0.64247508, 0.22156003, 0.83725087,
        0.34822256, 0.85136123, 0.10809935, 0.71635658, 0.25571548],
       [0.20748773, 0.46070909, 0.36964608, 0.03939377, 0.73815892,
        0.40473496, 0.87568826, 0.91904951, 0.54257154, 0.80341283],
       [0.96581807, 0.95296955, 0.5571837

In [14]:
#3: return only the odd rows of A
A[::2]

array([[0.9808211 , 0.1589114 , 0.07221844, 0.29289933, 0.65513343,
        0.65698947, 0.01231679, 0.65458402, 0.92888689, 0.31771102],
       [0.5937094 , 0.00675928, 0.10648805, 0.49602118, 0.90294554,
        0.45143813, 0.99901168, 0.40917879, 0.4047026 , 0.41391488],
       [0.90843183, 0.66761541, 0.84768839, 0.096319  , 0.05139835,
        0.75883449, 0.39422467, 0.07695471, 0.23141037, 0.84866362],
       [0.20748773, 0.46070909, 0.36964608, 0.03939377, 0.73815892,
        0.40473496, 0.87568826, 0.91904951, 0.54257154, 0.80341283],
       [0.07021368, 0.37506318, 0.01333613, 0.87884621, 0.54917412,
        0.47159906, 0.72513954, 0.69997354, 0.99015386, 0.85472674]])

In [15]:
#4: perform a matrix multiplication of A with it's transposed
A.dot(A.T)

array([[3.33150646, 1.97297773, 2.41208618, 2.36838059, 2.15856311,
        2.48051447, 2.43607463, 3.62051939, 2.71488332, 1.75612433],
       [1.97297773, 2.67825019, 2.27706274, 2.10023084, 2.04851763,
        2.04987648, 2.6201723 , 3.08910637, 2.42436101, 1.76025888],
       [2.41208618, 2.27706274, 3.12958163, 2.33506881, 1.94112895,
        2.77439769, 2.83743761, 3.33188207, 2.95567942, 2.49979877],
       [2.36838059, 2.10023084, 2.33506881, 2.65825119, 1.92456683,
        1.95470295, 2.02953314, 3.01852224, 2.38881654, 1.49828431],
       [2.15856311, 2.04851763, 1.94112895, 1.92456683, 3.51239908,
        2.71552413, 2.38159803, 3.41269752, 2.09047056, 1.6274214 ],
       [2.48051447, 2.04987648, 2.77439769, 1.95470295, 2.71552413,
        3.63858527, 2.94055476, 4.05002842, 2.78794775, 2.59705904],
       [2.43607463, 2.6201723 , 2.83743761, 2.02953314, 2.38159803,
        2.94055476, 3.65352107, 3.79034188, 3.32539886, 2.28242577],
       [3.62051939, 3.08910637, 3.3318820

In [20]:
#5: compute the matrix inverse of A
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.24780605, -0.08695437,  1.46317579, -0.40404569,  0.26654766,
        -0.15109286, -0.41161608,  0.47190535, -0.59680949, -0.87219237],
       [ 0.02973183,  1.16060926, -0.66110079,  0.00460153, -0.40594315,
         2.18729415, -0.37119   , -0.80110397,  0.25034191, -1.17908147],
       [-0.59950332, -1.52306111, -1.23942197,  1.02524   ,  0.47084922,
        -1.34017547,  1.04158096,  0.8976527 , -0.32314442,  1.72755176],
       [-0.49327055, -0.37092456, -0.35584898,  0.93902295, -0.07477327,
        -0.01030791, -0.38251094,  0.11734591,  0.57460993,  0.2484897 ],
       [ 0.49736543,  0.25265831, -0.75634869,  0.81824581, -0.58854766,
         1.72805135,  0.55119378, -1.53040154, -0.09053915, -0.10591949],
       [ 0.47876209,  0.96066241, -1.05138428,  0.04712493,  0.21535576,
         0.05678273, -0.53385569, -0.63837607,  0.37542033,  0.89850023],
       [-0.65754881,  0.06281948,  1.48767205, -0.86859755,  0.14224141,
        -0.76532301, -0.35612571,  0.94677937

In [16]:
#6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
np.where(A > 0.5, A/2, A)

array([[0.49041055, 0.1589114 , 0.07221844, 0.29289933, 0.32756671,
        0.32849474, 0.01231679, 0.32729201, 0.46444345, 0.31771102],
       [0.37258478, 0.40761305, 0.04598827, 0.21164715, 0.30157051,
        0.45044304, 0.38222845, 0.41999457, 0.013556  , 0.36561257],
       [0.2968547 , 0.00675928, 0.10648805, 0.49602118, 0.45147277,
        0.45143813, 0.49950584, 0.40917879, 0.4047026 , 0.41391488],
       [0.41054547, 0.13065452, 0.13905245, 0.43836544, 0.48683184,
        0.28988388, 0.28369693, 0.33020686, 0.04976711, 0.29454154],
       [0.45421592, 0.33380771, 0.42384419, 0.096319  , 0.05139835,
        0.37941724, 0.39422467, 0.07695471, 0.23141037, 0.42433181],
       [0.32598854, 0.39189971, 0.32123754, 0.22156003, 0.41862544,
        0.34822256, 0.42568061, 0.10809935, 0.35817829, 0.25571548],
       [0.20748773, 0.46070909, 0.36964608, 0.03939377, 0.36907946,
        0.40473496, 0.43784413, 0.45952476, 0.27128577, 0.40170641],
       [0.48290903, 0.47648477, 0.2785918

In [19]:
#7: compute the singular value decomposition of A
u,s,v = np.linalg.svd(A)
#7.1: plot the singular values
s

array([5.20173673, 1.44224928, 1.34740056, 1.12148846, 1.06680862,
       0.78026956, 0.70129953, 0.48544901, 0.25153924, 0.19800997])

In [21]:
#7.2: reconstruct A' by using only the top 5 singular values
np.dot(v.transpose(),np.dot(np.diag(s**-1),u.transpose()))

array([[ 0.24780605, -0.08695437,  1.46317579, -0.40404569,  0.26654766,
        -0.15109286, -0.41161608,  0.47190535, -0.59680949, -0.87219237],
       [ 0.02973183,  1.16060926, -0.66110079,  0.00460153, -0.40594315,
         2.18729415, -0.37119   , -0.80110397,  0.25034191, -1.17908147],
       [-0.59950332, -1.52306111, -1.23942197,  1.02524   ,  0.47084922,
        -1.34017547,  1.04158096,  0.8976527 , -0.32314442,  1.72755176],
       [-0.49327055, -0.37092456, -0.35584898,  0.93902295, -0.07477327,
        -0.01030791, -0.38251094,  0.11734591,  0.57460993,  0.2484897 ],
       [ 0.49736543,  0.25265831, -0.75634869,  0.81824581, -0.58854766,
         1.72805135,  0.55119378, -1.53040154, -0.09053915, -0.10591949],
       [ 0.47876209,  0.96066241, -1.05138428,  0.04712493,  0.21535576,
         0.05678273, -0.53385569, -0.63837607,  0.37542033,  0.89850023],
       [-0.65754881,  0.06281948,  1.48767205, -0.86859755,  0.14224141,
        -0.76532301, -0.35612571,  0.94677937